apiVersion: apps/v1
kind: Deployment
metadata:
  name: "iperf3-client-deployment"
  namespace: "iperf3-operator-ns"
  ladbels:
    app: "iperf3"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "iperf3"
  template:
    metadata:
      labels:
        app: "iperf3"
    spec:
      containers:
        - name: "iperf3-client"
          image: "iperf3:latest"
          command: iperf3-clinet.sh
          ports:
              name: iperf3-client

