---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - operator.nbt.pl
  resources:
  - iperfoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.nbt.pl
  resources:
  - iperfoperators/finalizers
  verbs:
  - update
- apiGroups:
  - operator.nbt.pl
  resources:
  - iperfoperators/status
  verbs:
  - get
  - patch
  - update
